version: '3.8'

services:
  factorio:
    build: .
    container_name: factorio-server
    ports:
      - "34197:34197/udp"  # Game port
      - "27015:27015/tcp"  # Query port
    volumes:
      - ~/factorio-server:/app/factorio
    environment:
      - FACTORIO_SERVER_SETTINGS=/app/factorio/server-settings.json
      - FACTORIO_SERVER_NAME=MyFactorioServer
      - FACTORIO_AUTO_SAVE_INTERVAL=10  # Auto-save interval in minutes
      - FACTORIO_ALLOW_INCOMPATIBLE_MODS=true  # Allow incompatible mods
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 240M
    tty: true                   # Allocate a pseudo-TTY
    stdin_open: true            # Keep stdin open
